version: '2'
services:
  rabbitmq:
    container_name: rabbitmq
    build: ./tools/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"

  mysql:
    build: ./tools/mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

